---
  doom-dqn:
    env_name: "/mnt/vanguard/git/ViZDoom-master/scenarios/deadly_corridor.cfg"
    visible: False
    reward_factor: 0.001

    input_shape: [84, 84]
    window_length: 4
    fps: 4
    grade: False

    double: True
    fixed: True
    use_per: True

    memory_capacity: 100000
    memory_alpha: 0.6
    memory_eps: 0.01

    learning_rate: 0.0001
    batch_size: 32
    gamma: 0.99
    update_after_actions: 100
    update_target_network: 3000
    tau: 0.08

    epsilon: 1.0
    epsilon_random_frames: 5000
    epsilon_greedy_frames: 50000
    epsilon_min: 0.0001
    epsilon_max: 1.0
    epsilon_annealer: (epsilon_max - epsilon_min)

  atari-policy:
    env_name: "PongDeterministic-v4"
    visible: True
    min_max: [-21, 21]

    input_shape: [84, 84]
    window_length: 4
    grade: True

    learning_rate: 0.000025
    gamma: 0.99
    update_after_actions: 0
