---
  ENV_NAME: "/mnt/vanguard/git/ViZDoom-master/scenarios/defend_the_center.cfg"
  INPUT_SHAPE: (84, 84)
  WINDOW_LENGTH: 4
  FPS: 4
  GRADE: True

  DOUBLE: True
  FIXED_Q: False

  EPSILON: 1.0
  EPSILON_RANDOM_FRAMES: 5000
  EPSILON_GREEDY_FRAMES: 50000
  EPSILON_MIN: 0.0001
  EPSILON_MAX: 1.0
  EPSILON_ANNEALER: (EPSILON_MAX - EPSILON_MIN)

  MAX_MEMORY_LENGTH: 50000
  BATCH_SIZE: 32
  GAMMA: 0.99
  UPDATE_AFTER_ACTIONS: 100
  UPDATE_TARGET_NETWORK: 3000
  TAU: 0.08
