---
  pong-dqn:
    env_name: "PongNoFrameskip-v4"
    visible: True
    reward_factor: 1
    min_max: [-21, 21]

    input_shape: [84, 84]
    window_length: 4
    fps: 4
    grade: True

    double: True
    fixed: False
    use_per: False

    memory_capacity: 1000000
    memory_alpha: 0.6
    memory_eps: 0.01

    learning_rate: 0.00025
    batch_size: 32
    gamma: 0.99
    update_after_actions: 4
    update_target_network: 10000
    tau: 0.08

    epsilon: 1.0
    epsilon_random_frames: 50000
    epsilon_greedy_frames: 1000000
    epsilon_min: 0.1
    epsilon_max: 1.0
    epsilon_annealer: (epsilon_max - epsilon_min)

  doom-dqn-defend_the_center:
    env_name: "/mnt/vanguard/git/ViZDoom-master/scenarios/defend_the_center.cfg"
    visible: True
    reward_factor: 1
    min_max: [0, 100]

    input_shape: [84, 84]
    window_length: 4
    fps: 4
    grade: False

    double: True
    fixed: True
    use_per: True

    memory_capacity: 100000
    memory_alpha: 0.6
    memory_eps: 0.01

    learning_rate: 0.0001
    batch_size: 32
    gamma: 0.99
    update_after_actions: 100
    update_target_network: 3000
    tau: 0.08

    epsilon: 1.0
    epsilon_random_frames: 5000
    epsilon_greedy_frames: 100000
    epsilon_min: 0.0001
    epsilon_max: 1.0
    epsilon_annealer: (epsilon_max - epsilon_min)

  doom-dqn-health_gathering:
    env_name: "/mnt/vanguard/git/ViZDoom-master/scenarios/health_gathering.cfg"
    visible: True
    reward_factor: 0.001
    min_max: [0, 1000]

    input_shape: [84, 84]
    window_length: 4
    fps: 4
    grade: False

    double: True
    fixed: True
    use_per: True

    memory_capacity: 100000
    memory_alpha: 0.6
    memory_eps: 0.01

    learning_rate: 0.0001
    batch_size: 32
    gamma: 0.99
    update_after_actions: 100
    update_target_network: 3000
    tau: 0.08

    epsilon: 1.0
    epsilon_random_frames: 5000
    epsilon_greedy_frames: 100000
    epsilon_min: 0.0001
    epsilon_max: 1.0
    epsilon_annealer: (epsilon_max - epsilon_min)

  doom-dqn-deadly_corridor:
    env_name: "/mnt/vanguard/git/ViZDoom-master/scenarios/deadly_corridor.cfg"
    visible: True
    reward_factor: 0.001
    min_max: [0, 10]

    input_shape: [84, 84]
    window_length: 4
    fps: 4
    grade: False

    double: True
    fixed: True
    use_per: True

    memory_capacity: 100000
    memory_alpha: 0.6
    memory_eps: 0.01

    learning_rate: 0.0001
    batch_size: 32
    gamma: 0.99
    update_after_actions: 100
    update_target_network: 3000
    tau: 0.08

    epsilon: 1.0
    epsilon_random_frames: 5000
    epsilon_greedy_frames: 100000
    epsilon_min: 0.0001
    epsilon_max: 1.0
    epsilon_annealer: (epsilon_max - epsilon_min)
