---

  pong-policy:
    env_name: "PongNoFrameskip-v4"
    visible: True
    min_max: [-21, 21]

    input_shape: [84, 84]
    window_length: 4
    fps: 4
    grade: True

    learning_rate: 0.000025
    gamma: 0.99
    update_after_actions: 0
